[project]
name = "app"
version = "0.1.0"

requires-python = ">=3.13"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.group.dev.dependencies]
ruff = "^0.12.3"

[tool.ruff]
line-length = 100
select = ["E", "F", "W", "I"]
